### ISSUE TITLE
Which sample is SRR3493407? N0030 or N0015?

### ISSUE THREAD

**Issue by haodongchen** [qiaseq/smcounter-v2-paper#2]
In the Supplementary Material of the biorxiv paper, SRR3493407 is sample N0030. However, based on here https://trace.ddbj.nig.ac.jp/DRASearch/run?acc=SRR3493407, this sample is labeled as n0015_L001_fastq.

**Comment by haodongchen** [comment]
Also, would it be possible to upload the bed files for N0015 and N0030? Thanks!

**Comment by rpadmanabhan** [comment]
Sorry for the confusion, SRR3493407 is N0015. N0030 is SRR3493403. I updated the README on this repository with all the Data URLs , please use those to download the relevant files. The N0015 and N0030 bed files are also uploaded.

**Comment by haodongchen** [comment]
Thank you for your clarification!
